### ISSUE TITLE
"list" argument must be an Array of Buffers

### ISSUE THREAD

**Issue by brandyjin** [chriso/nginx-parser#16]
I called method with `parser.read(_path, function(row){})`. and then go in 

```
Parser.prototype.stream = function (stream, iterator, callback) {
    var self = this, overflow = new Buffer(0), complete = false;
    stream.on('data', function (data) {
        var buffer = Buffer.concat(overflow, data), newline = 0;
        for (var i = 0, len = buffer.length; i < len; i++) {
            if (buffer[i] === 10) {
                self.parseLine(buffer.slice(newline, i), iterator);
                newline = i + 1;
            }
        }
        overflow = buffer.slice(newline);
    });
    ...
```

showed me a error message:
"list" argument must be an Array of Buffers。

The overflow wasn't setted value. data was an array.
Could you answer my question?
Thank you very much.

**Comment by chriso** [comment]
Can you provide some code and/or test data to reproduce the error?

**Comment by brandyjin** [comment]
`var NginxParser = require('nginxparser');  
var source = '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" "$http_x_forwarded_for"';
var parser = new NginxParser(source);
// _path : The path of a log file. 
parser.read(_path, function(row){
//        console.log("row: ", row);
        var obj = url.parse(row.request);
}`
Log file content：
127.0.0.1 - - [11/May/2016:16:57:53 +0800] "GET /v_19rrgy5z28.html HTTP/1.1" 200 70343 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1"

I sended a request to run this code.

Is that ok?

**Comment by chriso** [comment]
Fixed by https://github.com/chriso/nginx-parser/pull/15
